---
swagger: "2.0"
info:
  version: "v1"
  title: "My API"
host: "localhost:8080"
basePath: "/"
tags:
- name: "Library API"
schemes:
- "http"
- "https"
paths:
  /books:
    get:
      tags:
      - "Library API"
      summary: "Get all books"
      description: ""
      operationId: "getBooks"
      parameters: []
      responses:
        "200":
          description: "Successfully retrieved list of books"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Book"
        "400":
          description: "Validation failed. Bad input data."
    post:
      tags:
      - "Library API"
      summary: "Create new book"
      description: ""
      operationId: "addBook"
      parameters:
      - in: "body"
        name: "body"
        description: "Book to be created containing all necessary parameters"
        required: true
        schema:
          $ref: "#/definitions/Book"
      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: "#/definitions/Book"
        "201":
          description: "Successfully created book"
        "400":
          description: "Invalid input"
definitions:
  Book:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
        example: 1
        description: "Book ID"
      name:
        type: "string"
        example: "The Great Gatsby"
        description: "Book name"
    description: "Book entity"
